---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-web-service
spec:
  replicas: 5
  selector:
    matchLabels:
      name: go-web-service
  template:
    metadata:
      labels:
        name: go-web-service
    spec:
      containers:
      - name: application
        image: gnvshanessa/matching-service:latest
        imagePullPolicy: Always
        ports:
          - containerPort: 8080