---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bemypet
spec:
  replicas: 5
  selector:
    matchLabels:
      name: bemypet
  template:
    metadata:
      labels:
        name: bemypet
    spec:
      containers:
      - name: application
        image: gnvshanessa/matching-service:latest
        imagePullPolicy: Always
        ports:
          - containerPort: 8080